### ISSUE TITLE
Publish on Chrome Store

### ISSUE THREAD

**Issue by Max-the-Cat** [pranav-prakash/RokuCast#10]
Hi Pranav,
I've tried your Chrome app and it's really great.
Would you be willing to publish RokuCast on the Chrome Store?

Here's the developer link (if you don't have it)
https://chrome.google.com/webstore/developer/dashboard

Let us know if this is something you are ok with.

**Comment by pranav-prakash** [comment]
Hi,

I hesitated to publish this on the chrome store because it might violate some ToS somewhere (plus roku might not like their trademarked name being used). I also haven't found the time to add in feature enhancements and fix youtube support so for the time being the project has kind of stagnated.

As a workaround for having to close the developer mode popup box every time on application start, you could try publishing the extension to only be visible to tester accounts (https://developer.chrome.com/webstore/publish#testaccounts) which would make it only visible to you on the chrome store.

**Comment by nathanstuart01** [comment]
Amazing work on this, thanks for making it available. Any chance it could support flash players?
