### ISSUE TITLE
roku express

### ISSUE THREAD

**Issue by sastani** [pranav-prakash/RokuCast#14]
is this supposed to work with all rokus? didn't work with roku express

**Comment by pranav-prakash** [comment]
Yeah it should — What's the video you're trying to cast? What happens when you try to do so?

**Comment by sastani** [comment]
![rokucast](https://cloud.githubusercontent.com/assets/10406106/19917801/9c29141a-a083-11e6-9071-410e8f79f139.png)
When I hover over the cast icon in the extension, and click on it, nothing happens...

**Comment by pranav-prakash** [comment]
Ah, YouTube is one site that doesn't work well with this extension.

See 
https://github.com/pranav-prakash/RokuCast/issues/8
https://github.com/pranav-prakash/RokuCast/issues/11

for more detailed technical information if you wish but the gist of it is that 

> Google changed the playback method so that it no longer directly accesses the mp4 in the video element — rather, it now plays it one chuck at a time from a segment of the video stored locally in memory, and the video element points to a MediaSource object instead of an mp4.

One is to use a user agent switcher like so:

>Youtube to Roku Player, I recommend you use the extension [User-Agent Switcher for Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg/related). In Options => Permanent Spoof List => adds Youtube.com as a domain and iPhone 6 as user agent string

But this adds a bit of inconvenience since it will be formatted for mobile. Alternatively, YouTube has its own cast functionality where you just need to install the corresponding YouTube app on the roku player.
