### ISSUE TITLE
Casting google video URLs

### ISSUE THREAD

**Issue by jaykilly** [pranav-prakash/RokuCast#20]
Hi,

After downloading the rokucast initially I was able to cast pretty much anything I wanted to using the .crx file.  I tried using it today however it stopped working.  I tried both files that you offered and still can't get it to work.  I'm having a similar issue that another person had on here (video will try to load but end up saying "failed to play" and I have an HD tv).  Any help would be greatly appreciated.

**Comment by jaykilly** [comment]
Would also like to add theres only 1 laptop that is able to actually cast to the tv, every other one is not able to.

**Comment by pranav-prakash** [comment]
Hm.. can you give an example of a video file you are trying to cast?

Also when you say you tried "both files that [I] offered", are you referring to the playOnRoku and Production branches?

**Comment by jaykilly** [comment]
I'm trying to play movies on https://solarmovie.sc.  I'm able to watch on there on another laptop but not the one im currently using.  And yes I am referring to the playonroku and production brancehes

**Comment by pranav-prakash** [comment]
Ok so this is definitely connected with https://github.com/pranav-prakash/RokuCast/issues/18

The video URLs are in the format of `https://redirector.googlevideo.com/videoplayback?...` which redirects to the actual mp4.

However, google has (or recently added?) something in place so that it will actually redirect only if you are the one who originally accessed it (that is, trying to open the link from another browser or the Roku will result in a 403 denied). 

Somewhat interestingly a few times I *was* able to access the URL from another client after originally loading it in chrome. Maybe google is doing A/B testing and that one laptop of yours is excluded?

Also, are you able to play solarmovies videos from another browser such as Firefox or Safari? Chrome seems to be the only one able to do so for me.

---

Ok so as for solutions, a temporary fix specifically for solarmovies is to try selecting the openload server on the right side of the video player of solarmovies.

I'm working on a (somewhat hacky) fix which involves asking chrome to resolve the redirect before sending it to the roku. Interestingly that resolved URL can be accessed from anywhere without a problem.

**Comment by pranav-prakash** [comment]
Ok fixed in the playOnRoku branch. 

I'll merge the changes into the other branch (production, which uses the separate receiver app) eventually.

**Comment by jaykilly** [comment]
Hey pranav,  im still not able to get it to work.

**Comment by jaykilly** [comment]
Disregard the last message.  I re downloaded the playonroku file and it is
working!  Thanks a alot man really appreciate the help.

**Comment by pranav-prakash** [comment]
No problem! Glad to see it's working.
