### ISSUE TITLE
Cast no longer working?

### ISSUE THREAD

**Issue by bearsnacks** [pranav-prakash/RokuCast#24]
I hit the cast button on html5 videos and my roku will act like it's about to load the video then the screen just goes back to the home screen. I've tried numerous videos on numerous websites and non of them work. I'm not sure if I'm doing something wrong on my end or if something has changed in the past month or 2? I had no issues before that

**Comment by pranav-prakash** [comment]
I haven't changed anything on my end in the past two months. Do you have an example video for me to test with?

Also please provide the model and OS version of your Roku.

**Comment by bearsnacks** [comment]
https://solarmoviez.to/movie/kong-skull-island-19739/596071-14/watching.html here is an example for a movie link. I use two different Rokus. One is Roku 3 and the other is a Roku express.  Version 7.6

**Comment by pranav-prakash** [comment]
Odd - it's working for me. You're using the [playOnRoku](https://github.com/pranav-prakash/RokuCast/tree/playOnRoku) branch right?

Since you say that the problem appeared only recently, it's possible that some update to the Roku broke  or changed the format of the `play on roku` videoplayer (usually used for casting from the Roku app on phones) that this branch depends on.

Could you instead try the (master)[https://github.com/pranav-prakash/RokuCast/tree/master] branch. (That branch uses it's own independent companion app. Follow the instructions to sideload the app to your roku. You will also have to delete your current chrome extension and reinstall the one from that branch.

First try that and see if it works. If it doesn't the app will allow you to collect debugging info by telneting into the roku on port 8085.

**Comment by bearsnacks** [comment]
So I did the Master branch and that worked. Not sure why the regular version didn't.

**Comment by pranav-prakash** [comment]
Alright cool. I think there was one other person for whom that was the case too. I'm not sure why it happens though.
