### ISSUE TITLE
Roku add links by URL

### ISSUE THREAD

**Issue by dough321** [pranav-prakash/RokuCast#26]
First of all this is a great extension. I wonder if you can create something like "Plex IT" functionality. Like the channel is attached to a specific email address. Users can email video urls to that specific email address and those videos show up in the channel on Roku to view. Plex has this functionality for Roku and it's called watch later queue. 
https://support.plex.tv/hc/en-us/articles/201175406-Submit-to-your-Watch-Later-queue-via-Email
and here are the supported sites.
https://github.com/plexinc-plugins/Services.bundle/tree/master/Contents/Service%20Sets
I don't think m3u8 works also Youtube for users without running plex server is broken right now. Let me know if you need more details.

**Comment by pranav-prakash** [comment]
>I wonder if you can create something like "Plex IT" functionality. Like the channel is attached to a specific email address.

That's certainly possible, although it's a bit outside the scope of the project. If you would like to try to implement it, here's one possible way it could work. First you would set up a server (either on your local network — if you have a raspberry pi or something similar laying around — or on the cloud using ec2/azure/etc.) and have a database attached to that from which it could read and serve up an xml/json file containing your queued videos. You would have to modify the app to reach out and fetch this xml/json file on startup. 

Then for the email portion you could use IFFT or something along to trigger a POST request to your server with the url, and the server would automatically parse the website (perhaps using headless chrome?) and extract the video url and save it to the database. 

>I don't think m3u8 works
Do you have a sample site to test with. In most cases hls/m3u8 videos should work fine.

>also Youtube for users 
Yes  youtube casting only works if useragent is set to mobile, for reasons noted in the readme. I haven't bothered much in fixing it because there are endless ways to cast youtube these days, including using the native roku youtube app.
