### ISSUE TITLE
code license

### ISSUE THREAD

**Issue by theAeon** [pranav-prakash/RokuCast#53]
Hi-currently looking into porting @dgreuel's extension to firefox-but am wary of doing so without a license.

As it appears his is forked from this, if you could copyleft this extension it would copyleft his as a result.

Please lmk if you can add a license.md.

**Comment by pranav-prakash** [comment]
I believe dgreuel's implementation is a clean-slate rewrite, and doesn't use any of the components in this extension. 

Because this particular extension relies on `libvget` (as discussed here https://github.com/pranav-prakash/RokuCast/issues/34) which is not open-sourced, I don't believe I am able to copyleft this repo.

However, since dgreuel's implementation seems to be a clean rewrite that doesn't share any code, I think you could try asking him if he'd be willing to copyleft his.

(Also, doesn't Firefox have webextension support meaning that his version should work with minimal modifications?)

**Comment by pranav-prakash** [comment]
Ah actually I guess the `https://github.com/dgreuel/RokuKast/blob/master/src/roku.ts` is indeed shared with his fork. Luckily since _that_ part was written by me, I can add a license to just that specific piece of the code (I don't think it can be a gpl-esque copyleft license though since those are viral and require open-sourcing the entire repo). If there were other pieces that were shared, please let me know and I'll add the license to those as well (assuming they were written by me).

Would that be sufficient for your use-case (you'll still have to ask dgreuel to license the parts that were written by him though).

**Comment by theAeon** [comment]
I reached out the other day-he appears to be mildly dead.

Seems there's an implied MIT license on 99% of his repository because of [this](https://github.com/martellaj/chrome-extension-react-typescript-boilerplate) repository. Copylefting just roku.ts would work quite well-not sure what to do about the rest of it though. I wonder if there's a license that would propagate to his /src folder?

**Comment by pranav-prakash** [comment]
>I reached out the other day-he appears to be mildly dead.

He still appears to be active on github – assuming you already tried his email, maybe open an issue on the repo? 

>Seems there's an implied MIT license on 99% of his repository 

That's only for that specific library though, right? And since the MIT license isn't viral, it wouldn't cover the rest of the stuff in the `src` folder.

(Also I don't know if copyleft licenses apply retroactively. If you have an unlicensed repo A from which a repo B is forked, and then A adds a copyleft license, does that now apply to B as well? I would think not since the forking happened before a license was added).

---

Also, by "porting" I assume you mean publishing to the firefox add-on repos (since the extension itself should mostly work fine as-in in Firefox since it only seems to use standard webextension apis). If it's only for personal use you could just self-sign or whatever the equivalent for Firefox is (although I've heard they've made it harder to run extensions not from the web store).

**Comment by theAeon** [comment]
> 
> 
> > I reached out the other day-he appears to be mildly dead.
> 
> He still appears to be active on github – assuming you already tried his email, maybe open an issue on the repo?

yeah, thats what i did haha

> > Seems there's an implied MIT license on 99% of his repository
> 
> That's only for that specific library though, right? And since the MIT license isn't viral, it wouldn't cover the rest of the stuff in the `src` folder.

Right. I'm wondering how deeply it links into your roku.ts, is all.

> Also, by "porting" I assume you mean publishing to the firefox add-on repos (since the extension itself should mostly work fine as-in in Firefox since it only seems to use standard webextension apis). If it's only for personal use you could just self-sign or whatever the equivalent for Firefox is (although I've heard they've made it harder to run extensions not from the web store).

Yeah. Only real issue is that the jquery is so out of date that AMO won't publish it. Easy to fix.

I would like to publish it if at all possible, though.

**Comment by pranav-prakash** [comment]
I've gone ahead and licensed my `background.js` file (from which his `roku.ts` appears to be derived) under 0BSD which should be compatible with essentially any other license.

I guess the rest is up to dgreuel then.
