### ISSUE TITLE
Mostly not working

### ISSUE THREAD

**Issue by ldblake** [pranav-prakash/RokuCast#8]
This is mostly not working for me. 

Setup: 
PMS Version 0.9.15.3 
Roku 3
Chrome 48.0.2564.109 m

The webm video on the provided sample page won't load. The other two videos load. Anything I have tried on Youtube won't load. Dailymotion videos won't load. The only videos that will consistently load are on Liveleak. The other videos start to load for a spit second and then stop. Thanks for your work on this and for any help.

**Comment by pranav-prakash** [comment]
I don't believe Roku supports WebM as a playable media format so casting webm files will never work.

As for YouTube, a few months ago it used to work but then Google changed the playback method so that it no longer directly accesses the mp4 in the video element — rather, it now plays it one chuck at a time from a segment of the video stored locally in memory, and the video element points to a MediaSource object instead of an mp4.

Services like youtube-dl and YoutubeCenter still seem to be able to download the mp4, so there is still likely a way to get it. I *can* add a special case for YouTube, however I don't see the point since YouTube has its own native casting functionality built in (download the youtube app on the roku to use it).

DailyMotion is a bit weird. If you use a desktop, they serve up their videos using a flash player from which it isn't always so easy to extract the video url (the site parser I'm using as the underlying framework, libvget, does try to do this but isn't always successful). If you access the mobile version of the site, however, (using a user-agent switcher for example) then DailyMotion serves up the video in a html5 video container which is directly castable.

In general almost all sites using a video container to serve up videos as per the html5 spec should work reliably. Those using flash will have a lower success rate depending upon how they implemented it. Those using silverlight or have implemented DRM will never work.

I'm looking into other ways to scrape the URLs more reliably but I've been kind of busy.

**Comment by Amandysha** [comment]
Hello @ldblake ! For send videos from Youtube to Roku Player, I recommend you use the extension [User-Agent Switcher
for Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg/related). In Options => Permanent Spoof List => adds Youtube.com as a domain and iPhone 6 as **user agent string**

**Comment by ldblake** [comment]
I'm using the Google Cast extension:

https://goo.gl/6mgBj5

It will cast Youtube videos to the Roku as well as Chromecast.

**Comment by Amandysha** [comment]
Thanks @ldblake ! I know but sometimes not working fine and is very slow. I prefer use the RokuCast extension and  User-Agent
 Switcher
