### ISSUE TITLE
New backend to support ssdp

### ISSUE THREAD

**Issue by jacobEAdamson** [pranav-prakash/RokuCast#9]
Hey, I like your addon, but I noticed you didn't have automatic detection of Roku devices. I took the liberty of building a chrome app that user would install that will automatically send out ssdp queries and keep track of what devices reply. I also built a extension/web side javascript library that you can use to get the current devices (just as simple as ssdp.GetDevices).

Let me know if you would like to see it or are interested in using it (I have a working demo that automatically streams twitch streams to the roku twitch app, where you can select which roku you want from a drop down menu)

**Comment by pranav-prakash** [comment]
Hmm this looks quite useful! When I get a chance I'll replace the manual ip entry with this.

Thanks!

**Comment by joshtch** [comment]
I wanted this feature, so I implemented it [in my own fork](https://github.com/pranav-prakash/RokuCast/compare/playOnRoku...joshtch:playOnRoku). I'll submit a PR soon, but I did it by modifying `options.html` and `scripts/options.js`, using [the example](https://github.com/jacobEAdamson/ssdp-chrome/blob/master/ContentScript/content_script.js) for reference. I also copied `ssdp.js` from [jacobEAdamson/ssdp-chrome](https://github.com/jacobEAdamson/ssdp-chrome), though if the SSDP-Chrome API will not change, a direct link to the repo code would be better. (I made some other changes, too, which is why there are three commits.)

**Comment by pranav-prakash** [comment]
That's sweet! Thanks so much. I'll merge the PR

EDIT: Merged! Thank you once again!
